### ISSUE TITLE
Creating a key pair requires a lot of CPU time and is unstable

### ISSUE THREAD

**Issue by eauxxs** [LNP-BP/ssi#1]
for example, create a bip340 keypair:

https://github.com/LNP-BP/ssi/blob/2dbf7ed9c2be87e08fb395725e665d06bdda3489/src/bip340.rs#L55-L66

The loop here to find a public key whose last two bytes meet the requirements is unreasonable. When you are lucky, it may be fast, but it will take about 5 seconds. When you are unlucky, it may even take up a CPU core for 30 seconds just to save two bytes of space. I think this is extremely unreasonable. If you agree, I can try to fix this problem.

**Comment by dr-orlovsky** [comment]
We make the data about the used signing scheme and blockchain a part of the key, to save two bytes. Removing that will increase the size of the SSI string on ~four chars.

Since the keys are rarely created and frequently used, such CPU load is better tradeoff than longer key string.

**Comment by eauxxs** [comment]
@dr-orlovsky  Find a private key using POW like mining... If this cannot be changed, I have a backward compatible method. Currently, the last 2 bytes must meet the requirements, that is, 16 bits. I think this can be reduced. For example, there are two types of algo (ed25519 and bip340) and chain (bitcoin and liquid), so 2 bits are enough. You have reserved 16 bits for compatibility with future types. This can greatly increase the speed of generating key pairs by orders of magnitude.

**Comment by eauxxs** [comment]
I think field chain can keep 2 bits, algo can keep 3 bits. What is your idea?

**Comment by dr-orlovsky** [comment]
SSI will be adding more signature methods and curves over the time - like it happened with PGP/GPG and SSH. It is unavoidalbe. Maybe we can fit into one byte, but certainly not less.

But why are you concerned with time for generating a key? PGP were taking even much longer for RSA keys... It is normal to have long-time generation for identity

**Comment by eauxxs** [comment]
I just have a bad experience with it. I want to put forward some ideas to try to see if it can be improved. Since you have a good reason, I will close this issue.
